<?php

namespace Tests\Framework\Http;

use Framework\Http\Request;
use PHPUnit\Framework\TestCase;

class RequestTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $_GET = [];
        $_POST = [];
    }

    public function testQueryParams() : void
    {
        $_GET = $data = [
          'name' => 'Abdulaziz',
          'age' => 22,
        ];

        $request = new Request();

        self::assertEquals($data, $request->getQueryParams());

    }

    public function testEmpty(){
        $req = new Request();

        self::assertEquals([], $req->getQueryParams());
        self::assertNull( $req->getParsedBody());
    }

}